### ISSUE TITLE
Recursion Directory

### ISSUE THREAD

**Issue by gauravarora011** [OpenGenus/cosmos#1079]
what about a directory for recursive algos:

```
Flood fill Algorithm
Number of paths
Water Overflow
Josephus problem
```

**Comment by AdiChat** [comment]
Recursion is more of an implementation technique rather than a domain in itself. More over all the problems can be incorporated in other sections. 

If we create a category for recursion, then the problem of duplicate code at multiple locations will be more severe. 

Currently, we do accept codes in the same language for the same problem expressing different implementation techniques. So, the need for recursion as a category seems redundant at the moment 👍
