### ISSUE TITLE
Quicksort implementation is duplicated

### ISSUE THREAD

**Issue by faiyaz26** [OpenGenus/cosmos#1429]
Quicksort implementation is given both [here](https://github.com/OpenGenus/cosmos/tree/master/code/sorting/quick_sort), [here](https://github.com/OpenGenus/cosmos/tree/master/code/divide_conquer/Quick_Sort) and [here](https://github.com/OpenGenus/cosmos/tree/master/code/divide_conquer/quick_sort)

I think rather having two different directories for the same thing is redundant. Rather this [directory](https://github.com/OpenGenus/cosmos/tree/master/code/divide_conquer/Quick_Sort) should contain a Readme.md file which will share the real directory location.

**Comment by FrankKair** [comment]
You're right. I can see why there are two paths for Quicksort, since it does belong to divide and conquer, but also, err... it's a sorting algorithm.

I agree with you in the sense that we should have only one directory, but I don't think it should be the one you suggested. The directory doesn't follow the naming convention that this project uses. And the other one has more files already... I mean, we could move them around, but what would be the point anyway.

I think it's really up to @AdiChat 😆

**Comment by AdiChat** [comment]
We work as a community :family_man_woman_girl_boy: . If some of us think that it should be merged, then it will be merged 😃 

The idea behind duplicate categories in different paths is to keep each path complete in itself. I think it will distract a user if he or she has to navigate from one path to another to gain knowledge of a particular category. 

One possible solution is to maintain a list of such duplicate files and sync them once and ensure future pull requests maintains this.
