### ISSUE TITLE
Travis build for c programs failing due to Windows specific code

### ISSUE THREAD

**Issue by yedhink** [OpenGenus/cosmos#3962]
**This is a(n):**
- [ ] New algorithm
- [x] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**
* The travis build(as of Job #1944.1) is again failing due to errors from the file code/sorting/src/sleep_sort/sleep_sort.c
* The code is windows specific. Our build system for travis ci targets only the linux os. That's the cause of error

**Proposals:**
* My suggestion is to port the code for sleep sort to play nicely with linux os. I can update the existing algorithm. Then we can add a documentation on how to run c-programs for testing in local system and specifically mention that the current build doesn't support windows specific code.
* Or add a build system config for windows specific files(might cost some time)

@arnavb what do you suggest?

**Comment by arnavb** [comment]
Since we want users to be able to use sleep sort on any OS, I think that conditional compilation with `#ifdef`, `#endif`, etc. would be the best option to ensure maximum portability. What we can do is create a wrapper around the platform specific function (`sleep`, I believe) and use this technique. The function called in the algorithm will expand to the right system call on the right os.

@yedhink Would you like to try doing this? Make sure to reference this issue when doing so.

**Comment by yedhink** [comment]
@arnavb Sure thing. I will try my best

**Comment by yedhink** [comment]
@arnavb Hope this PR fixes the build issues. See if it can be approved.

**Comment by yedhink** [comment]
@arnavb any responses regarding the pr #3964  ? What changes are required?
