### ISSUE TITLE
Bubble Sort in C++ using Recursion

### ISSUE THREAD

**Issue by aayanksinghai** [OpenGenus/cosmos#4438]
**This is a(n):**

- [ ] New algorithm
- [x] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

**Comment by abhishekkansal** [comment]
Please assign this issue to me. I am interested in updating the algorithm to a newer one.

**Comment by Ayush7-BIT** [comment]
Sir!! i can work on this issue..?please assign me..

**Comment by Swa4nali** [comment]
Please assign this issue to me..

**Comment by ishikabansal04** [comment]
sir. please assign me this issue.

**Comment by SDakshit** [comment]
Sir, I would like to work on this. Please assign it to me.

**Comment by kashika3101** [comment]
sir, please assign this issue to me in c++

**Comment by kashika3101** [comment]
sir, please assign this issue to me

**Comment by Varshney200** [comment]
please assign this issue to me

**Comment by suchi12j** [comment]
please assign it to me

**Comment by Meenakshi2000** [comment]
assign me this please

**Comment by arnavb** [comment]
For now @Varshney200 will work on this issue since they created the first PR.

**Comment by arnavb** [comment]
Closed in #4650

**Comment by Ayush7-BIT** [comment]
Sir today I will make all those PR for sure just don’t assign those issue to anyone else and thank you for your patience! Sent from Mail for Windows 10 From: Arnav BorborahSent: 22 March 2020 18:00To: OpenGenus/cosmosCc: Ayush Pandey; CommentSubject: Re: [OpenGenus/cosmos] Bubble Sort in C++ using Recursion (#4438) Closed #4438.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
